package main;


import page.Connexion;
import page.Nouveau_mot_de_passe;
import page.Creation_de_compte;
import page.Paged_accueil;
import page.Liste_Repas;
import page.Ajout_Repas;
import page.Modification_Repas;
import page.Liste_Recette;
import bdd.Requete_bdd;
import bdd.BDD;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author r.topolovac
 */
public class MainFrame extends javax.swing.JFrame {
    static private Connexion pageConnexion;
    static private Nouveau_mot_de_passe pageNouveaumot_de_passe;
    static private Creation_de_compte pageCreation_de_compte;
    static private Paged_accueil paged_Accueil;
    static private Liste_Repas pageListeRepas;
    static private Ajout_Repas pageAjout_Repas;
    static private Modification_Repas pageModification_Repas;
    static private Liste_Recette pageListeRecette;
    static private Requete_bdd bddRequest;
    public boolean isUserConnected = false;  // Variable pour vérifier si l'utilisateur est connecté
    private int userId;
    
    

    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
          
    }
    
    
    public int getId_Utilisateur(){
        return userId;
    }
    
    public void setId_Utilisateur(int id) {
    this.userId = id;
    
    }

    public boolean isUserConnected() {
    return isUserConnected;
    }

    public void setUserConnected(boolean isConnected) {
        this.isUserConnected = isConnected;
    }
    

    public void SwithPanel(String panelName){
        if (!isUserConnected){
            if (panelName.equals("pageCreation_de_compte") || panelName.equals("pageConnexion")) {
                switch (panelName) {
                case "pageConnexion" -> this.setContentPane(pageConnexion);
                case "pageCreation_de_compte" -> this.setContentPane(pageCreation_de_compte);
                }
            }else{
                // Autoriser l'accès à la page de création de compte et à la page de connexion
                // Si l'utilisateur n'est pas connecté et essaie d'accéder à une autre page,
                // afficher un message pour lui dire que l'accès est impossible.
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Vous devez être connecté pour accéder à cette page.",
                    "Accès refusé",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;  // Ne pas changer de page si l'utilisateur n'est pas connecté
                }
        }else{
            switch (panelName){
                case "pageConnexion" -> this.setContentPane(pageConnexion);
                case "pageNouveaumot_de_passe" -> this.setContentPane(pageNouveaumot_de_passe);
                case "paged_Accueil" -> this.setContentPane(paged_Accueil);
                case "pageListeRepas" -> this.setContentPane(pageListeRepas);
                case "pageAjout_Repas" -> this.setContentPane(pageAjout_Repas);
                case "pageModification_Repas" -> this.setContentPane(pageModification_Repas);
                case "pageListeRecette" -> this.setContentPane(pageListeRecette);
            }
        }
        
        // Mettre à jour l'interface utilisateur
        this.revalidate();
        this.repaint();
    }
    
    
    
    public Requete_bdd getBDD() {return this.bddRequest; }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Accueil = new javax.swing.JMenu();
        Menu_Accueil = new javax.swing.JMenuItem();
        Menu_AjoutRepas = new javax.swing.JMenu();
        Page_Liste_Repas = new javax.swing.JMenuItem();
        Page_Ajout_Repas = new javax.swing.JMenuItem();
        Page_Liste_Recette = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Page_Modif_mdp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Accueil.setText("Menu");

        Menu_Accueil.setText("Accueil");
        Menu_Accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_AccueilActionPerformed(evt);
            }
        });
        Accueil.add(Menu_Accueil);

        Menu_AjoutRepas.setText("Liste_Repas");

        Page_Liste_Repas.setText("Page de Liste des Repas");
        Page_Liste_Repas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Page_Liste_RepasActionPerformed(evt);
            }
        });
        Menu_AjoutRepas.add(Page_Liste_Repas);

        Page_Ajout_Repas.setText("Page d'Ajout de repas");
        Page_Ajout_Repas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Page_Ajout_RepasActionPerformed(evt);
            }
        });
        Menu_AjoutRepas.add(Page_Ajout_Repas);

        Accueil.add(Menu_AjoutRepas);

        Page_Liste_Recette.setText("Liste Recette");
        Page_Liste_Recette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Page_Liste_RecetteActionPerformed(evt);
            }
        });
        Accueil.add(Page_Liste_Recette);

        jMenu1.setText("Compte");

        Page_Modif_mdp.setText("Modification_mot de passe");
        Page_Modif_mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Page_Modif_mdpActionPerformed(evt);
            }
        });
        jMenu1.add(Page_Modif_mdp);

        Accueil.add(jMenu1);

        jMenuBar1.add(Accueil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_AccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_AccueilActionPerformed
        // TODO add your handling code here:
        SwithPanel("paged_Accueil");
        // Mettre à jour l'interface utilisateur
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_Menu_AccueilActionPerformed

    private void Page_Modif_mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Page_Modif_mdpActionPerformed
        // TODO add your handling code here:
        SwithPanel("pageNouveaumot_de_passe");
        // Mettre à jour l'interface utilisateur
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_Page_Modif_mdpActionPerformed

    private void Page_Liste_RepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Page_Liste_RepasActionPerformed
        // TODO add your handling code here:
        SwithPanel("pageListeRepas");
        // Mettre à jour l'interface utilisateur
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_Page_Liste_RepasActionPerformed

    private void Page_Ajout_RepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Page_Ajout_RepasActionPerformed
        // TODO add your handling code here:
        SwithPanel("pageAjout_Repas");
        // Mettre à jour l'interface utilisateur
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_Page_Ajout_RepasActionPerformed

    private void Page_Liste_RecetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Page_Liste_RecetteActionPerformed
        // TODO add your handling code here:
        SwithPanel("pageListeRecette");
        // Mettre à jour l'interface utilisateur
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_Page_Liste_RecetteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame newMainFrame = new MainFrame();
                
                bddRequest = new Requete_bdd();
                if(bddRequest.Connexion())
                    System.out.print("Connexion OK\n");
                else
                    System.out.print("Connexion NON EFFECTUEE\n");
                
                pageConnexion = new Connexion(newMainFrame);
                pageNouveaumot_de_passe = new Nouveau_mot_de_passe(newMainFrame);
                pageCreation_de_compte = new Creation_de_compte(newMainFrame, bddRequest);               
                paged_Accueil = new Paged_accueil(newMainFrame);
                pageListeRepas = new Liste_Repas(newMainFrame);
                pageAjout_Repas = new Ajout_Repas(newMainFrame);
                pageModification_Repas = new Modification_Repas(newMainFrame);
                pageListeRecette = new Liste_Recette(newMainFrame);
                
                newMainFrame.setContentPane(pageConnexion);
                newMainFrame.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Accueil;
    private javax.swing.JMenuItem Menu_Accueil;
    private javax.swing.JMenu Menu_AjoutRepas;
    private javax.swing.JMenuItem Page_Ajout_Repas;
    private javax.swing.JMenuItem Page_Liste_Recette;
    private javax.swing.JMenuItem Page_Liste_Repas;
    private javax.swing.JMenuItem Page_Modif_mdp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
