package page;

import bdd.BDD;
import controller.Repas_Controller;
import controller.Repas_Recette_Controller;
import entity.Type_Repas_Item;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import main.MainFrame;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */



/**
 *
 * @author amagl
 */
public class Liste_Repas extends javax.swing.JPanel {
    private MainFrame mainJFrame;
    private Repas_Recette_Controller table;
    private Repas_Controller repas_controller;
    private DefaultComboBoxModel repas_date;
    public int id_repas;
 
    // Déclarer le modèle de la liste de recettes
    private DefaultTableModel repasTable;
    


    /** Creates new form Liste_Repas */
    public Liste_Repas(MainFrame newJFrame) {
        mainJFrame = newJFrame; 
        table = new Repas_Recette_Controller(mainJFrame.getBDD());
        repas_controller = new Repas_Controller(mainJFrame.getBDD());
      
        initComponents();
        
        chargerListeRepas(); // <-- Rafraîchit directement la table au lancement
  
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Filtre_Date1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Filtre_Date2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BoutonAjout_ListeRepas = new javax.swing.JButton();
        BoutonSupprimer_ListeRepas = new javax.swing.JButton();
        BoutonModif_ListeRepas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Repas_recette = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Filtre date :");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Smart Shopping");
        jLabel2.setToolTipText("");

        Filtre_Date1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Filtre_Date1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Filtre_Date1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Filtre_Date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtre_Date1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("à");
        jLabel4.setToolTipText("");

        Filtre_Date2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Filtre_Date2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Filtre_Date2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Filtre_Date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filtre_Date2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Liste de repas");
        jLabel5.setToolTipText("");

        BoutonAjout_ListeRepas.setText("Ajouter un Repas");
        BoutonAjout_ListeRepas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAjout_ListeRepasActionPerformed(evt);
            }
        });

        BoutonSupprimer_ListeRepas.setText("Supprimer un Repas");
        BoutonSupprimer_ListeRepas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSupprimer_ListeRepasActionPerformed(evt);
            }
        });

        BoutonModif_ListeRepas.setText("Modifier un Repas");
        BoutonModif_ListeRepas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonModif_ListeRepasActionPerformed(evt);
            }
        });

        Repas_recette.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date du repas", "Type de repas", "Personne(s)", "Recette(s)"
            }
        ));
        jScrollPane1.setViewportView(Repas_recette);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(BoutonAjout_ListeRepas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonModif_ListeRepas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(BoutonSupprimer_ListeRepas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Filtre_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Filtre_Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(368, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filtre_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filtre_Date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 431, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonSupprimer_ListeRepas)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoutonAjout_ListeRepas)
                        .addComponent(BoutonModif_ListeRepas)))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(164, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Filtre_Date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtre_Date1ActionPerformed
        // TODO add your handling code here:
        chargerListeRepas();
        
    }//GEN-LAST:event_Filtre_Date1ActionPerformed

    private void Filtre_Date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filtre_Date2ActionPerformed
        // TODO add your handling code here:
        chargerListeRepas();

    }//GEN-LAST:event_Filtre_Date2ActionPerformed

    private void BoutonAjout_ListeRepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAjout_ListeRepasActionPerformed
        // TODO add your handling code here:
           mainJFrame.SwithPanel("pageAjout_Repas");

            this.revalidate();
            this.repaint();
    }//GEN-LAST:event_BoutonAjout_ListeRepasActionPerformed

    private void BoutonSupprimer_ListeRepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSupprimer_ListeRepasActionPerformed
        // TODO add your handling code here:
        //définir en premier le modèle de la table 
        DefaultTableModel model = (DefaultTableModel) Repas_recette.getModel();
        //supprimer les données existantes

        // Vérifier si une ligne est sélectionnée
        int selectedRow = Repas_recette.getSelectedRow();
        if (selectedRow != -1){//si une ligne est sélectionner 

            int repasId = (int)model.getValueAt(selectedRow, 1);
            // Appeler la méthode suppressionRecette dans la BDD pour supprimer la recette
            boolean success = mainJFrame.getBDD().supprimerRepas(repasId);

            if(success){
                //Ont supprime la ligne sélectionnée
                model.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Ligne supprimée avec succès !");
                }else {
                    if(model.getRowCount()==0){
                        JOptionPane.showMessageDialog(this, "La table est vide");
                    }else{
                        //si la table n'est pas vide et qu'une ligne ou plusieurs lignes n'est pas sélectionner 
                        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne pour");
                        }
                }
        }
    }//GEN-LAST:event_BoutonSupprimer_ListeRepasActionPerformed

    private void BoutonModif_ListeRepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonModif_ListeRepasActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = Repas_recette.getSelectedRow();
        
        // Si la ligne sélectionné est inférieur (si aucune ligne n'est sélectionné alors) à 0
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this,"Veuillez choisir un repas à modifier");  // Alors on renvoie ce message à l'utilisateur
        }
        
        // On créer une objet qui récupérera le numéro de la ligne sélectionner dans la collone 0 (ID)
        Object object = Repas_recette.getModel().getValueAt(selectedRow, 0); // Colonne 0 = ID (caché)

        // On vérifie si Object renvoie bien un type Integer
        if(object instanceof Integer) {
            // on transforme l'object en Integer
            id_repas = (Integer) object;
            repas_controller.setId_Repas(id_repas);
            // Appel vers la fenêtre de modification du repas
            System.out.println(id_repas);
        } else {
            JOptionPane.showMessageDialog(this, "Erreur : l'ID du repas est invalide.");
        }

        mainJFrame.SwithPanel("pageModification_Repas");
    }//GEN-LAST:event_BoutonModif_ListeRepasActionPerformed

    private void Filtre_Date1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Filtre_Date1AncestorAdded
        // TODO add your handling code here:
        // TODO add your handling code here:
        int id_utilisateur = mainJFrame.getId_Utilisateur();
        repas_date = repas_controller.ListerDateRepas(id_utilisateur);
        
        Filtre_Date1.removeAllItems();
        Filtre_Date1.setModel(repas_date);
        
        // Sélectionne la date du jour si elle est dans le modèle
        String dateAujourdhui = new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
        Filtre_Date1.setSelectedItem(dateAujourdhui);
    }//GEN-LAST:event_Filtre_Date1AncestorAdded

    private void Filtre_Date2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Filtre_Date2AncestorAdded
        // TODO add your handling code here:
        int id_utilisateur = mainJFrame.getId_Utilisateur();
        repas_date = repas_controller.ListerDateRepas(id_utilisateur);
        
        Filtre_Date2.removeAllItems();
        Filtre_Date2.setModel(repas_date);
        
        // Sélectionne la date du jour si elle est dans le modèle
        String dateAujourdhui = new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
        Filtre_Date2.setSelectedItem(dateAujourdhui);
    }//GEN-LAST:event_Filtre_Date2AncestorAdded
              
    private void chargerListeRepas() {
    String date1 = (String) Filtre_Date1.getSelectedItem();
    String date2 = (String) Filtre_Date2.getSelectedItem();
    int id_utilisateur = mainJFrame.getId_Utilisateur();

    if (date1 != null && date2 != null) {
        repasTable = table.ListerRepas_Utilisateur(id_utilisateur, date1, date2);
        Repas_recette.setModel(repasTable);
        
        // Cacher la colonne ID (colonne 0)
        Repas_recette.getColumnModel().getColumn(0).setMinWidth(0);
        Repas_recette.getColumnModel().getColumn(0).setMaxWidth(0);
        Repas_recette.getColumnModel().getColumn(0).setWidth(0);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAjout_ListeRepas;
    private javax.swing.JButton BoutonModif_ListeRepas;
    private javax.swing.JButton BoutonSupprimer_ListeRepas;
    private javax.swing.JComboBox<String> Filtre_Date1;
    private javax.swing.JComboBox<String> Filtre_Date2;
    private javax.swing.JTable Repas_recette;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
