/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package page;

import javax.swing.*;
import java.util.ArrayList;


import bdd.BDD;
import bdd.Requete_bdd;
import javax.swing.JList;
import main.MainFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel; // Import nécessaire pour utiliser ListSelectionModel



/**
 *
 * @author amagl
 */
public class Liste_Recettes extends javax.swing.JFrame {
    private MainFrame mainJFrame;
    private BDD bdd;
    private JList<String> ListedesRecette_ListeRecette;
    /**
     * Creates new form Liste_Recet
     */
    public Liste_Recettes(MainFrame newJFrame) {
        mainJFrame = newJFrame;
        bdd=new BDD();
      
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Field_LaRecette = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableau_Recette = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Liste_Recette = new javax.swing.JList<>();
        Ajouter_Recette = new javax.swing.JButton();
        Modifier_Recette = new javax.swing.JButton();
        Supprimer_Recette = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Smart Shopping");
        jLabel2.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Liste de recettes");
        jLabel6.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" Recettes :");
        jLabel12.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ingrédient pour la recette :");
        jLabel7.setToolTipText("");

        Tableau_Recette.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom Recette", "Ingrédient (1 personnes)"
            }
        ));
        jScrollPane1.setViewportView(Tableau_Recette);

        Liste_Recette.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Liste_Recette.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Liste_RecetteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Liste_Recette.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Liste_RecetteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Liste_Recette);

        Ajouter_Recette.setText("Ajouter une Recette");

        Modifier_Recette.setText("Modifier une Recette");

        Supprimer_Recette.setText("Supprimer une Recette");
        Supprimer_Recette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supprimer_RecetteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Ajouter_Recette)
                                .addGap(72, 72, 72)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Field_LaRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Modifier_Recette)
                                .addGap(227, 227, 227)
                                .addComponent(Supprimer_Recette)
                                .addGap(83, 83, 83)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field_LaRecette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouter_Recette, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modifier_Recette, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Supprimer_Recette, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Liste_RecetteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Liste_RecetteAncestorAdded
        // TODO add your handling code here:
        // Définir un nouveau modèle avec deux colonnes : "Nom" et "ID"
        // Créer un nouveau modèle de liste
        DefaultListModel<String> model = new DefaultListModel<>();
        Liste_Recette.setModel(model);

        // Récupérer les nouvelles données depuis la BDD
        ArrayList<ArrayList<Object>> listeRecette = mainJFrame.getBDD().listerRecette();

        // Ajouter les nouvelles lignes au modèle
        for (ArrayList<Object> ligne : listeRecette) {
            String recetteInfo = ligne.get(0) + " "; // Exemple : "Nom de la recette (ID: 123)"
            model.addElement(recetteInfo);
        }

        // Mettre à jour l'interface utilisateur
        this.revalidate();
        this.repaint();

    }//GEN-LAST:event_Liste_RecetteAncestorAdded

    private void Liste_RecetteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Liste_RecetteMouseClicked
        // TODO add your handling code here:
        /*int selectedRow = ListedesRecette_ListeRecette.getAnchorSelectionIndex(); // Récupère l'index de la ligne sélectionnée
        if (selectedRow != -1) { // Vérifie qu'une ligne est bien sélectionnée
        DefaultListModel model = (DefaultListModel) ListedesRecette_ListeRecette.getModel();
        Object value = model.get(selectedRow); // Exemple : récupérer la valeur de la première colonne
        System.out.println("Valeur sélectionnée : " + value);}*/

    }//GEN-LAST:event_Liste_RecetteMouseClicked

    private void Supprimer_RecetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supprimer_RecetteActionPerformed
        // TODO add your handling code here:
        /*int selectedRow = ListedesRecette_ListeRecette.getAnchorSelectionIndex(); // Récupère l'index de la ligne sélectionnée
        if (selectedRow != -1) { // Vérifie qu'une ligne est bien sélectionnée
            DefaultListModel model = (DefaultListModel) ListedesRecette_ListeRecette.getModel();
            Object value = model.get(selectedRow); // Exemple : récupérer la valeur de la première colonne
            System.out.println("Valeur sélectionnée : " + value);
        }*/
    }//GEN-LAST:event_Supprimer_RecetteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Ajouter_Recette;
    public javax.swing.JFormattedTextField Field_LaRecette;
    public javax.swing.JList<String> Liste_Recette;
    public javax.swing.JButton Modifier_Recette;
    public javax.swing.JButton Supprimer_Recette;
    public javax.swing.JTable Tableau_Recette;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
