/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package page;

import main.MainFrame;

/**
 *
 * @author amagl
 */
public class Mes_Recettes extends javax.swing.JPanel {
    private MainFrame mainJFrame;

    /** Creates new form Ajout_Modification_Recette*/
    public Mes_Recettes(MainFrame newJFrame) {
        mainJFrame = newJFrame;
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BoutonCompte_Mes_Recettes = new javax.swing.JButton();
        BoutonMesRecettes_ListeRepas = new javax.swing.JButton();
        BoutonAccueil_MesRecettes = new javax.swing.JButton();
        BoutonAjoutsModif_ListeRepas = new javax.swing.JButton();
        Indicationdesrecettes_Mes_Recettes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listerecette_Mes_Recettes = new javax.swing.JList<>();
        Indicationrecette_Mes_Recettes = new javax.swing.JLabel();
        Indicationustensile_Mes_Recettes = new javax.swing.JLabel();
        Indicationingrédient_Mes_Recettes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Listeingrédient_Mes_Recettes = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        Listeustensile_Mes_Recettes = new javax.swing.JList<>();
        indicationsrecette_Mes_Recettes = new javax.swing.JFormattedTextField();
        Indicationitempsdepréparation_Mes_Recettes = new javax.swing.JLabel();
        indicationstempsdepréparation_Mes_Recettes = new javax.swing.JFormattedTextField();

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Smart Shopping");
        jLabel2.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mes Recettes");
        jLabel5.setToolTipText("");

        BoutonCompte_Mes_Recettes.setText("Compte");
        BoutonCompte_Mes_Recettes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonCompte_Mes_RecettesActionPerformed(evt);
            }
        });

        BoutonMesRecettes_ListeRepas.setText("Liste Repas");
        BoutonMesRecettes_ListeRepas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMesRecettes_ListeRepasActionPerformed(evt);
            }
        });

        BoutonAccueil_MesRecettes.setText("Accueil");
        BoutonAccueil_MesRecettes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAccueil_MesRecettesActionPerformed(evt);
            }
        });

        BoutonAjoutsModif_ListeRepas.setText("Ajout/Modification Repas");
        BoutonAjoutsModif_ListeRepas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAjoutsModif_ListeRepasActionPerformed(evt);
            }
        });

        Indicationdesrecettes_Mes_Recettes.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        Indicationdesrecettes_Mes_Recettes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Indicationdesrecettes_Mes_Recettes.setText("Recettes");
        Indicationdesrecettes_Mes_Recettes.setToolTipText("");

        Listerecette_Mes_Recettes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Listerecette_Mes_Recettes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Listerecette_Mes_Recettes);

        Indicationrecette_Mes_Recettes.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        Indicationrecette_Mes_Recettes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Indicationrecette_Mes_Recettes.setText("Recette :");
        Indicationrecette_Mes_Recettes.setToolTipText("");

        Indicationustensile_Mes_Recettes.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        Indicationustensile_Mes_Recettes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Indicationustensile_Mes_Recettes.setText("Ustensiles :");
        Indicationustensile_Mes_Recettes.setToolTipText("");

        Indicationingrédient_Mes_Recettes.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        Indicationingrédient_Mes_Recettes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Indicationingrédient_Mes_Recettes.setText("Ingrédients :");
        Indicationingrédient_Mes_Recettes.setToolTipText("");

        Listeingrédient_Mes_Recettes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Listeingrédient_Mes_Recettes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(Listeingrédient_Mes_Recettes);

        Listeustensile_Mes_Recettes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Listeustensile_Mes_Recettes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(Listeustensile_Mes_Recettes);

        indicationsrecette_Mes_Recettes.setText("Namethisrecipe");

        Indicationitempsdepréparation_Mes_Recettes.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 10)); // NOI18N
        Indicationitempsdepréparation_Mes_Recettes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Indicationitempsdepréparation_Mes_Recettes.setText("Temps de préparation :");
        Indicationitempsdepréparation_Mes_Recettes.setToolTipText("");

        indicationstempsdepréparation_Mes_Recettes.setText("preparation time");
        indicationstempsdepréparation_Mes_Recettes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indicationstempsdepréparation_Mes_RecettesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonAccueil_MesRecettes, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonMesRecettes_ListeRepas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371)
                        .addComponent(BoutonCompte_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BoutonAjoutsModif_ListeRepas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317)
                .addComponent(indicationsrecette_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Indicationitempsdepréparation_Mes_Recettes)
                .addGap(18, 18, 18)
                .addComponent(indicationstempsdepréparation_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(795, 795, 795)
                            .addComponent(Indicationrecette_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(221, 221, 221))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(201, 201, 201)
                                    .addComponent(Indicationdesrecettes_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Indicationingrédient_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Indicationustensile_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(13, 13, 13)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoutonCompte_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(indicationsrecette_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(BoutonAjoutsModif_ListeRepas))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BoutonAccueil_MesRecettes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoutonMesRecettes_ListeRepas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Indicationitempsdepréparation_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indicationstempsdepréparation_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(Indicationrecette_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Indicationustensile_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Indicationingrédient_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                            .addContainerGap(103, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Indicationdesrecettes_Mes_Recettes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonCompte_Mes_RecettesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonCompte_Mes_RecettesActionPerformed
        // TODO add your handling code here:
        mainJFrame.SwithPanel("pageConnexion");
    }//GEN-LAST:event_BoutonCompte_Mes_RecettesActionPerformed

    private void BoutonMesRecettes_ListeRepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMesRecettes_ListeRepasActionPerformed
        // TODO add your handling code here:
        mainJFrame.SwithPanel("pageListeRepas");
    }//GEN-LAST:event_BoutonMesRecettes_ListeRepasActionPerformed

    private void BoutonAccueil_MesRecettesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAccueil_MesRecettesActionPerformed
        // TODO add your handling code here:
        mainJFrame.SwithPanel("pageAccueil");

    }//GEN-LAST:event_BoutonAccueil_MesRecettesActionPerformed

    private void BoutonAjoutsModif_ListeRepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAjoutsModif_ListeRepasActionPerformed
        // TODO add your handling code here:
        mainJFrame.SwithPanel("pageAjoutModifciationRepas");
    }//GEN-LAST:event_BoutonAjoutsModif_ListeRepasActionPerformed

    private void indicationstempsdepréparation_Mes_RecettesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indicationstempsdepréparation_Mes_RecettesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indicationstempsdepréparation_Mes_RecettesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAccueil_MesRecettes;
    private javax.swing.JButton BoutonAjoutsModif_ListeRepas;
    private javax.swing.JButton BoutonCompte_Mes_Recettes;
    private javax.swing.JButton BoutonMesRecettes_ListeRepas;
    private javax.swing.JLabel Indicationdesrecettes_Mes_Recettes;
    private javax.swing.JLabel Indicationingrédient_Mes_Recettes;
    private javax.swing.JLabel Indicationitempsdepréparation_Mes_Recettes;
    private javax.swing.JLabel Indicationrecette_Mes_Recettes;
    private javax.swing.JLabel Indicationustensile_Mes_Recettes;
    private javax.swing.JList<String> Listeingrédient_Mes_Recettes;
    private javax.swing.JList<String> Listerecette_Mes_Recettes;
    private javax.swing.JList<String> Listeustensile_Mes_Recettes;
    private javax.swing.JFormattedTextField indicationsrecette_Mes_Recettes;
    private javax.swing.JFormattedTextField indicationstempsdepréparation_Mes_Recettes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
